export const data = [
  {
    id: 1,
    txnId: "TXN1001",
    laneId: "L1",
    vehicleNo: "UP16AB1234",
    tag: "TAG001",
    passingTime: "2026-02-01 10:12:22",
    paymentType: "FASTag",
    paymentSubType: "Wallet",
    image: "img1.jpg",
    agencyApproved: "Pending",
    systemApproved: "Pending",
  },
  {
    id: 2,
    txnId: "TXN1002",
    laneId: "L2",
    vehicleNo: "DL08CD5678",
    tag: "TAG002",
    passingTime: "2026-02-01 10:15:12",
    paymentType: "Cash",
    paymentSubType: "Manual",
    image: "img2.jpg",
    agencyApproved: "Pending",
    systemApproved: "Pending",
  },
  {
    id: 3,
    txnId: "TXN1003",
    laneId: "L3",
    vehicleNo: "HR26EF3456",
    tag: "TAG003",
    passingTime: "2026-02-01 10:18:44",
    paymentType: "FASTag",
    paymentSubType: "Bank",
    image: "img3.jpg",
    agencyApproved: "Pending",
    systemApproved: "Approved",
  },
  {
    id: 4,
    txnId: "TXN1004",
    laneId: "L1",
    vehicleNo: "UP14GH9876",
    tag: "TAG004",
    passingTime: "2026-02-01 10:22:11",
    paymentType: "Card",
    paymentSubType: "Debit",
    image: "img4.jpg",
    agencyApproved: "Pending",
    systemApproved: "Pending",
  },
  {
    id: 5,
    txnId: "TXN1005",
    laneId: "L4",
    vehicleNo: "RJ19JK4321",
    tag: "TAG005",
    passingTime: "2026-02-01 10:25:56",
    paymentType: "FASTag",
    paymentSubType: "Wallet",
    image: "img5.jpg",
    agencyApproved: "Pending",
    systemApproved: "Approved",
  },
  {
    id: 6,
    txnId: "TXN1006",
    laneId: "L2",
    vehicleNo: "PB10LM8765",
    tag: "TAG006",
    passingTime: "2026-02-01 10:30:08",
    paymentType: "Cash",
    paymentSubType: "Manual",
    image: "img6.jpg",
    agencyApproved: "Pending",
    systemApproved: "Rejected",
  },
  {
    id: 7,
    txnId: "TXN1007",
    laneId: "L3",
    vehicleNo: "UP32NO1234",
    tag: "TAG007",
    passingTime: "2026-02-01 10:34:27",
    paymentType: "FASTag",
    paymentSubType: "Bank",
    image: "img7.jpg",
    agencyApproved: "Pending",
    systemApproved: "Approved",
  },
  {
    id: 8,
    txnId: "TXN1008",
    laneId: "L1",
    vehicleNo: "DL05PQ5678",
    tag: "TAG008",
    passingTime: "2026-02-01 10:38:10",
    paymentType: "Card",
    paymentSubType: "Credit",
    image: "img8.jpg",
    agencyApproved: "Pending",
    systemApproved: "Pending",
  },
  {
    id: 9,
    txnId: "TXN1009",
    laneId: "L4",
    vehicleNo: "HR51RS3456",
    tag: "TAG009",
    passingTime: "2026-02-01 10:42:52",
    paymentType: "FASTag",
    paymentSubType: "Wallet",
    image: "img9.jpg",
    agencyApproved: "Pending",
    systemApproved: "Approved",
  },
  {
    id: 10,
    txnId: "TXN1010",
    laneId: "L2",
    vehicleNo: "UP70TU9876",
    tag: "TAG010",
    passingTime: "2026-02-01 10:47:31",
    paymentType: "Cash",
    paymentSubType: "Manual",
    image: "img10.jpg",
    agencyApproved: "Pending",
    systemApproved: "Rejected",
  },
  {
    id: 11,
    txnId: "TXN1011",
    laneId: "L3",
    vehicleNo: "RJ14VW4321",
    tag: "TAG011",
    passingTime: "2026-02-01 10:51:14",
    paymentType: "FASTag",
    paymentSubType: "Bank",
    image: "img11.jpg",
    agencyApproved: "Pending",
    systemApproved: "Approved",
  },
  {
    id: 12,
    txnId: "TXN1012",
    laneId: "L1",
    vehicleNo: "PB08XY8765",
    tag: "TAG012",
    passingTime: "2026-02-01 10:55:33",
    paymentType: "Card",
    paymentSubType: "Debit",
    image: "img12.jpg",
    agencyApproved: "Pending",
    systemApproved: "Pending",
  },
  {
    id: 13,
    txnId: "TXN1013",
    laneId: "L4",
    vehicleNo: "UP65ZA1234",
    tag: "TAG013",
    passingTime: "2026-02-01 11:00:09",
    paymentType: "FASTag",
    paymentSubType: "Wallet",
    image: "img13.jpg",
    agencyApproved: "Pending",
    systemApproved: "Approved",
  },
  {
    id: 14,
    txnId: "TXN1014",
    laneId: "L2",
    vehicleNo: "DL11BC5678",
    tag: "TAG014",
    passingTime: "2026-02-01 11:04:48",
    paymentType: "Cash",
    paymentSubType: "Manual",
    image: "img14.jpg",
    agencyApproved: "Pending",
    systemApproved: "Rejected",
  },
  {
    id: 15,
    txnId: "TXN1015",
    laneId: "L3",
    vehicleNo: "HR29DE3456",
    tag: "TAG015",
    passingTime: "2026-02-01 11:08:27",
    paymentType: "FASTag",
    paymentSubType: "Bank",
    image: "img15.jpg",
    agencyApproved: "Pending",
    systemApproved: "Approved",
  },
];

export const Tdata = [
  {
    id: 1,
    plazaCode: "PZ001",
    plazaName: "Delhi Toll Plaza",
    image: "img1.jpg",
    cchTransId: "CCH1001",
    laneTransId: "LT2001",
    tag: "TAG001",
    vehPlate: "UP16AB1234",
    isAnpr: "Yes",
    anprPlate: "UP16AB1234",
    laneId: "L1",
    laneType: "FASTag",
    direction: "North",
    vehClass: "Car",
    avcClass: "Class1",
  },
  {
    id: 2,
    plazaCode: "PZ002",
    plazaName: "Noida Toll Plaza",
    image: "img2.jpg",
    cchTransId: "CCH1002",
    laneTransId: "LT2002",
    tag: "TAG002",
    vehPlate: "DL08CD5678",
    isAnpr: "Yes",
    anprPlate: "DL08CD5678",
    laneId: "L2",
    laneType: "Cash",
    direction: "South",
    vehClass: "Bus",
    avcClass: "Class3",
  },
  {
    id: 3,
    plazaCode: "PZ003",
    plazaName: "Ghaziabad Toll",
    image: "img3.jpg",
    cchTransId: "CCH1003",
    laneTransId: "LT2003",
    tag: "TAG003",
    vehPlate: "HR26EF3456",
    isAnpr: "No",
    anprPlate: "HR26EF3456",
    laneId: "L3",
    laneType: "FASTag",
    direction: "East",
    vehClass: "Truck",
    avcClass: "Class5",
  },
  {
    id: 4,
    plazaCode: "PZ004",
    plazaName: "Meerut Plaza",
    image: "img4.jpg",
    cchTransId: "CCH1004",
    laneTransId: "LT2004",
    tag: "TAG004",
    vehPlate: "UP14GH9876",
    isAnpr: "Yes",
    anprPlate: "UP14GH9876",
    laneId: "L1",
    laneType: "Card",
    direction: "West",
    vehClass: "Car",
    avcClass: "Class1",
  },
  {
    id: 5,
    plazaCode: "PZ005",
    plazaName: "Agra Toll",
    image: "img5.jpg",
    cchTransId: "CCH1005",
    laneTransId: "LT2005",
    tag: "TAG005",
    vehPlate: "RJ19JK4321",
    isAnpr: "Yes",
    anprPlate: "RJ19JK4321",
    laneId: "L4",
    laneType: "FASTag",
    direction: "North",
    vehClass: "Car",
    avcClass: "Class1",
  },
  {
    id: 6,
    plazaCode: "PZ006",
    plazaName: "Lucknow Plaza",
    image: "img6.jpg",
    cchTransId: "CCH1006",
    laneTransId: "LT2006",
    tag: "TAG006",
    vehPlate: "PB10LM8765",
    isAnpr: "No",
    anprPlate: "PB10LM8765",
    laneId: "L2",
    laneType: "Cash",
    direction: "South",
    vehClass: "Truck",
    avcClass: "Class5",
  },
  {
    id: 7,
    plazaCode: "PZ007",
    plazaName: "Kanpur Plaza",
    image: "img7.jpg",
    cchTransId: "CCH1007",
    laneTransId: "LT2007",
    tag: "TAG007",
    vehPlate: "UP32NO1234",
    isAnpr: "Yes",
    anprPlate: "UP32NO1234",
    laneId: "L3",
    laneType: "FASTag",
    direction: "East",
    vehClass: "Bus",
    avcClass: "Class3",
  },
  {
    id: 8,
    plazaCode: "PZ008",
    plazaName: "Mathura Toll",
    image: "img8.jpg",
    cchTransId: "CCH1008",
    laneTransId: "LT2008",
    tag: "TAG008",
    vehPlate: "DL05PQ5678",
    isAnpr: "Yes",
    anprPlate: "DL05PQ5678",
    laneId: "L1",
    laneType: "Card",
    direction: "West",
    vehClass: "Car",
    avcClass: "Class1",
  },
  {
    id: 9,
    plazaCode: "PZ009",
    plazaName: "Aligarh Toll",
    image: "img9.jpg",
    cchTransId: "CCH1009",
    laneTransId: "LT2009",
    tag: "TAG009",
    vehPlate: "HR51RS3456",
    isAnpr: "Yes",
    anprPlate: "HR51RS3456",
    laneId: "L4",
    laneType: "FASTag",
    direction: "North",
    vehClass: "Car",
    avcClass: "Class1",
  },
  {
    id: 10,
    plazaCode: "PZ010",
    plazaName: "Faridabad Toll",
    image: "img10.jpg",
    cchTransId: "CCH1010",
    laneTransId: "LT2010",
    tag: "TAG010",
    vehPlate: "UP70TU9876",
    isAnpr: "No",
    anprPlate: "UP70TU9876",
    laneId: "L2",
    laneType: "Cash",
    direction: "South",
    vehClass: "Truck",
    avcClass: "Class5",
  },
  {
    id: 11,
    plazaCode: "PZ011",
    plazaName: "Jaipur Toll",
    image: "img11.jpg",
    cchTransId: "CCH1011",
    laneTransId: "LT2011",
    tag: "TAG011",
    vehPlate: "RJ14VW4321",
    isAnpr: "Yes",
    anprPlate: "RJ14VW4321",
    laneId: "L3",
    laneType: "FASTag",
    direction: "East",
    vehClass: "Bus",
    avcClass: "Class3",
  },
  {
    id: 12,
    plazaCode: "PZ012",
    plazaName: "Chandigarh Toll",
    image: "img12.jpg",
    cchTransId: "CCH1012",
    laneTransId: "LT2012",
    tag: "TAG012",
    vehPlate: "PB08XY8765",
    isAnpr: "Yes",
    anprPlate: "PB08XY8765",
    laneId: "L1",
    laneType: "Card",
    direction: "West",
    vehClass: "Car",
    avcClass: "Class1",
  },
  {
    id: 13,
    plazaCode: "PZ013",
    plazaName: "Varanasi Toll",
    image: "img13.jpg",
    cchTransId: "CCH1013",
    laneTransId: "LT2013",
    tag: "TAG013",
    vehPlate: "UP65ZA1234",
    isAnpr: "Yes",
    anprPlate: "UP65ZA1234",
    laneId: "L4",
    laneType: "FASTag",
    direction: "North",
    vehClass: "Car",
    avcClass: "Class1",
  },
  {
    id: 14,
    plazaCode: "PZ014",
    plazaName: "Patna Toll",
    image: "img14.jpg",
    cchTransId: "CCH1014",
    laneTransId: "LT2014",
    tag: "TAG014",
    vehPlate: "DL11BC5678",
    isAnpr: "No",
    anprPlate: "DL11BC5678",
    laneId: "L2",
    laneType: "Cash",
    direction: "South",
    vehClass: "Truck",
    avcClass: "Class5",
  },
  {
    id: 15,
    plazaCode: "PZ015",
    plazaName: "Bhopal Toll",
    image: "img15.jpg",
    cchTransId: "CCH1015",
    laneTransId: "LT2015",
    tag: "TAG015",
    vehPlate: "HR29DE3456",
    isAnpr: "Yes",
    anprPlate: "HR29DE3456",
    laneId: "L3",
    laneType: "FASTag",
    direction: "East",
    vehClass: "Bus",
    avcClass: "Class3",
  },
  {
    id: 16,
    plazaCode: "PZ016",
    plazaName: "Indore Toll",
    image: "img16.jpg",
    cchTransId: "CCH1016",
    laneTransId: "LT2016",
    tag: "TAG016",
    vehPlate: "MP09FG6789",
    isAnpr: "Yes",
    anprPlate: "MP09FG6789",
    laneId: "L1",
    laneType: "Card",
    direction: "West",
    vehClass: "Car",
    avcClass: "Class1",
  },
  {
    id: 17,
    plazaCode: "PZ017",
    plazaName: "Nagpur Toll",
    image: "img17.jpg",
    cchTransId: "CCH1017",
    laneTransId: "LT2017",
    tag: "TAG017",
    vehPlate: "MH31HI2345",
    isAnpr: "Yes",
    anprPlate: "MH31HI2345",
    laneId: "L4",
    laneType: "FASTag",
    direction: "North",
    vehClass: "Car",
    avcClass: "Class1",
  },
  {
    id: 18,
    plazaCode: "PZ018",
    plazaName: "Pune Toll",
    image: "img18.jpg",
    cchTransId: "CCH1018",
    laneTransId: "LT2018",
    tag: "TAG018",
    vehPlate: "MH12JK5678",
    isAnpr: "No",
    anprPlate: "MH12JK5678",
    laneId: "L2",
    laneType: "Cash",
    direction: "South",
    vehClass: "Truck",
    avcClass: "Class5",
  },
  {
    id: 19,
    plazaCode: "PZ019",
    plazaName: "Hyderabad Toll",
    image: "img19.jpg",
    cchTransId: "CCH1019",
    laneTransId: "LT2019",
    tag: "TAG019",
    vehPlate: "TS09LM4321",
    isAnpr: "Yes",
    anprPlate: "TS09LM4321",
    laneId: "L3",
    laneType: "FASTag",
    direction: "East",
    vehClass: "Bus",
    avcClass: "Class3",
  },
  {
    id: 20,
    plazaCode: "PZ020",
    plazaName: "Bangalore Toll",
    image: "img20.jpg",
    cchTransId: "CCH1020",
    laneTransId: "LT2020",
    tag: "TAG020",
    vehPlate: "KA05NO9876",
    isAnpr: "Yes",
    anprPlate: "KA05NO9876",
    laneId: "L1",
    laneType: "Card",
    direction: "West",
    vehClass: "Car",
    avcClass: "Class1",
  },
];